import React from "react";
import { format } from "date-fns";

export default function Invoice({ booking }) {
  const serviceAmount = booking.service_amount || booking.budget || 1000;
  const platformFee = Math.round(serviceAmount * 0.10);
  const totalAmount = serviceAmount + platformFee;
  const invoiceNumber = booking.invoice_number || `${booking.id?.slice(0, 8)}-${Math.floor(Math.random() * 9999)}`;

  return (
    <div className="bg-white p-12 max-w-4xl mx-auto print:p-8">
      {/* Header */}
      <div className="flex justify-between items-start mb-12">
        <div>
          <h1 className="text-6xl font-black mb-2">INVOICE</h1>
          <p className="text-gray-600 text-lg">#{invoiceNumber}</p>
        </div>
        <div className="text-right">
          <h2 className="text-4xl font-black text-purple-600 mb-2">EVNT</h2>
          <p className="text-gray-500">Marketplace Facilitator</p>
        </div>
      </div>

      {/* Client Info & Date */}
      <div className="flex justify-between mb-12">
        <div>
          <h3 className="text-sm font-bold text-gray-500 mb-2">BILL TO</h3>
          <p className="text-xl font-bold">{booking.client_name}</p>
          <p className="text-gray-600">Ref: {booking.event_type}</p>
        </div>
        <div className="text-right">
          <h3 className="text-sm font-bold text-gray-500 mb-2">DATE ISSUED</h3>
          <p className="text-xl font-bold">{format(new Date(), "MMM dd, yyyy")}</p>
          <div className="mt-4">
            <span className="inline-block px-4 py-2 bg-green-100 text-green-800 font-bold rounded">
              PENDING
            </span>
          </div>
        </div>
      </div>

      {/* Line Items */}
      <div className="border-t-2 border-b-2 border-gray-300 py-4 mb-8">
        <div className="flex justify-between text-sm font-bold text-gray-400 mb-4">
          <div className="flex-1">Description</div>
          <div className="w-32 text-right">Amount</div>
        </div>

        {/* Service */}
        <div className="py-4 border-b border-gray-200">
          <div className="flex justify-between items-start">
            <div className="flex-1">
              <p className="text-xl font-bold mb-1">
                {booking.service_description || `${booking.vendor_name} Services`}
              </p>
              <p className="text-gray-500 text-sm">
                Event Date: {format(new Date(booking.event_date), "MMMM dd, yyyy")}
              </p>
            </div>
            <div className="w-32 text-right text-xl font-bold">
              ${serviceAmount.toLocaleString()}.00
            </div>
          </div>
        </div>

        {/* Platform Fee */}
        <div className="py-4 border-b-2 border-gray-800">
          <div className="flex justify-between items-start">
            <div className="flex-1">
              <p className="text-xl font-bold mb-1">Platform & Trust Fee</p>
              <p className="text-gray-400 text-sm">
                Includes Payment Processing & Escrow (10%)
              </p>
            </div>
            <div className="w-32 text-right text-xl font-bold">
              ${platformFee.toLocaleString()}.00
            </div>
          </div>
        </div>

        {/* Total */}
        <div className="flex justify-between items-center pt-6">
          <div className="text-2xl font-bold text-gray-400">Total</div>
          <div className="text-3xl font-black">
            ${totalAmount.toLocaleString()}.00
          </div>
        </div>
      </div>

      {/* Payment Info */}
      <div className="bg-gray-50 p-6 rounded-lg">
        <h3 className="font-bold text-lg mb-3">Payment Information:</h3>
        <p className="text-gray-700">
          Payment secured via Stripe Connect. Funds are held in escrow by EVNT Platform until 24 hours after the
          event completion date ({format(new Date(booking.event_date), "MMM dd, yyyy")}).
        </p>
        <p className="text-xs text-gray-400 text-center mt-4">
          Generated by EVNT Marketplace Solutions Inc.
        </p>
      </div>
    </div>
  );
}